package jp.komeko.order.inventory;

import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import javax.sql.DataSource;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * マイグレーション SQL を<b>本物の PostgreSQL で</b>流すテスト。
 *
 * <p><b>なぜ H2 のテストだけでは足りないのか</b><br>
 * 本番は PostgreSQL ＋ {@code ddl-auto: validate} です。
 * つまり<b>SQL が PostgreSQL で通らなければ、本番アプリは起動しません</b>。
 * しかも開発は H2 なので、デプロイするその瞬間まで気づけません。
 * 「起動しない」を初回デプロイの夜に発見するのは、いちばん高くつく気づき方です。
 *
 * <p>H2 のテスト（{@code MigrationSchemaTest}）は列の書き忘れを速く潰すためのもので、
 * こちらは<b>方言の違い</b>を潰すためのものです。役割が違うので両方あります。
 * H2 が通して PostgreSQL が落とすものの例:
 * <ul>
 *   <li>PostgreSQL の予約語を列名に使っている</li>
 *   <li>型の書き方が片方にしかない（{@code CLOB} など）</li>
 *   <li>採番の書き方が違う</li>
 * </ul>
 *
 * <p><b>Docker は要りません。</b>PostgreSQL の実体をテストの中で
 * サブプロセスとして起動します。初回だけ実行ファイルの取得に時間がかかります。
 *
 * <p><b>このテストで分からないこと</b><br>
 * 既存 13 テーブルとの整合（{@code validate}）までは見ていません。
 * それらは Flyway ではなく Hibernate が作ったもので、
 * 本番では V1 として「もうある」ことにしているためです。
 * ここで確かめるのは、<b>自分が書いた SQL が本番の DB で通るか</b>です。
 */
@DisplayName("マイグレーション SQL（本物の PostgreSQL）")
class PostgresMigrationTest {

    /**
     * 流す順番。本番と同じ順で、同じものを流す。
     * V3 は V2 が作ったテーブルに列を足すので、順番ごと確かめないと意味がない。
     */
    private static final String[] MIGRATIONS = {
            "db/migration/V2__inventory_step1.sql",
            "db/migration/V3__inventory_step2.sql",
            "db/migration/V4__inventory_step3.sql",
    };

    /**
     * V4 が外部キーで参照する既存テーブルの代役。
     *
     * <p>本番ではもう存在しているテーブルです。ここでは
     * 「V4 の外部キーが張れること」だけ確かめたいので最小限にしています。
     */
    private static final String MENU_ITEM_STUB = """
            CREATE TABLE menu_item (
                id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(60) NOT NULL
            );
            """;

    private static EmbeddedPostgres postgres;
    private static DataSource dataSource;

    @BeforeAll
    static void startPostgres() throws IOException {
        postgres = EmbeddedPostgres.builder().start();
        dataSource = postgres.getPostgresDatabase();
    }

    @AfterAll
    static void stopPostgres() throws IOException {
        if (postgres != null) {
            postgres.close();
        }
    }

    /** まっさらなスキーマを作り、そこにマイグレーションを流す。 */
    private Connection freshSchema(String schema) throws SQLException, IOException {
        Connection connection = dataSource.getConnection();
        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            statement.execute("CREATE SCHEMA " + schema);
            statement.execute("SET search_path TO " + schema);
            statement.execute(MENU_ITEM_STUB);
            for (String migration : MIGRATIONS) {
                statement.execute(new String(new ClassPathResource(migration).getInputStream()
                        .readAllBytes(), StandardCharsets.UTF_8));
            }
        }
        return connection;
    }

    /** そのテーブルの「列名 → 型」。PostgreSQL は識別子を小文字で保持する。 */
    private Map<String, String> columnsOf(Connection connection, String schema, String table)
            throws SQLException {
        Map<String, String> columns = new LinkedHashMap<>();
        String sql = """
                select column_name, data_type, is_nullable
                from information_schema.columns
                where table_schema = ? and table_name = ?
                order by ordinal_position
                """;
        try (var ps = connection.prepareStatement(sql)) {
            ps.setString(1, schema);
            ps.setString(2, table);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    columns.put(rs.getString(1), rs.getString(2));
                }
            }
        }
        return columns;
    }

    @Test
    @DisplayName("★ V2〜V4 が PostgreSQL で最後まで流れる（本番が起動できる、ということ）")
    void migrations_run_on_postgresql() throws Exception {
        try (Connection connection = freshSchema("mig_run")) {
            // 7 つのテーブルが全部できていること
            for (String table : List.of("tax_rate_period", "deduction_rate_period",
                    "purchase", "purchase_line", "ingredient", "item_alias",
                    "stocktake", "recipe_line")) {
                assertThat(columnsOf(connection, "mig_run", table))
                        .as("テーブル %s ができていない", table)
                        .isNotEmpty();
            }
        }
    }

    @Test
    @DisplayName("型が PostgreSQL 側でも想定どおり（validate が通る形になっている）")
    void column_types_are_what_the_entities_expect() throws Exception {
        try (Connection connection = freshSchema("mig_types")) {
            Map<String, String> purchase = columnsOf(connection, "mig_types", "purchase");

            // 金額は int（円）。数量だけ numeric、という規約が DB 側でも守られていること
            assertThat(purchase.get("total_amount")).isEqualTo("integer");
            assertThat(purchase.get("purchased_on")).isEqualTo("date");
            assertThat(purchase.get("stored_at")).isEqualTo("timestamp without time zone");
            assertThat(purchase.get("deleted")).isEqualTo("boolean");
            // AI の生の応答。長い文字列を H2 と PostgreSQL の両方で扱える書き方にしてある
            assertThat(purchase.get("ocr_json")).isEqualTo("character varying");

            Map<String, String> line = columnsOf(connection, "mig_types", "purchase_line");
            assertThat(line.get("amount")).isEqualTo("integer");
            // 0.5 パックがあり得るので数量は小数
            assertThat(line.get("quantity")).isEqualTo("numeric");
            assertThat(line.get("stock_qty")).isEqualTo("numeric");

            Map<String, String> stocktake = columnsOf(connection, "mig_types", "stocktake");
            // 「type」は PostgreSQL でも列名に使える（予約語ではない）ことの確認も兼ねる
            assertThat(stocktake.get("type")).isEqualTo("character varying");
            assertThat(stocktake.get("taken_on")).isEqualTo("date");
            assertThat(stocktake.get("quantity")).isEqualTo("numeric");
        }
    }

    @Test
    @DisplayName("採番が動き、外部キーが効く")
    void identity_and_foreign_keys_work() throws Exception {
        try (Connection connection = freshSchema("mig_use");
             Statement statement = connection.createStatement()) {

            statement.execute("SET search_path TO mig_use");

            statement.execute("""
                    INSERT INTO ingredient (name, unit, active, sort_order)
                    VALUES ('キャベツ', 'GRAM', false, 0)
                    """);
            long ingredientId;
            try (ResultSet rs = statement.executeQuery("SELECT id FROM ingredient")) {
                assertThat(rs.next()).isTrue();
                ingredientId = rs.getLong(1);
            }
            assertThat(ingredientId).isPositive();   // 採番が動いている

            statement.execute("""
                    INSERT INTO purchase
                      (purchased_on, store_name, total_amount, received_on, stored_at,
                       paper_retention_required, reg_verify_status, evidence_type,
                       deduction_rate_percent, payment_method, deleted)
                    VALUES
                      (DATE '2026-08-31', 'テスト商店', 766, DATE '2026-08-31',
                       TIMESTAMP '2026-08-31 21:00:00', FALSE, 'CHECK_DIGIT_OK',
                       'SIMPLIFIED_INVOICE', 100, 'CASH', FALSE)
                    """);
            long purchaseId;
            try (ResultSet rs = statement.executeQuery("SELECT id FROM purchase")) {
                assertThat(rs.next()).isTrue();
                purchaseId = rs.getLong(1);
            }

            statement.execute("""
                    INSERT INTO purchase_line
                      (purchase_id, line_no, item_text, quantity, amount,
                       tax_rate_percent, category, ingredient_id, stock_qty)
                    VALUES
                      (%d, 1, 'ｷｬﾍﾞﾂ 1/2', 1.5, 216, 8, 'FOOD', %d, 1600.0)
                    """.formatted(purchaseId, ingredientId));

            try (ResultSet rs = statement.executeQuery(
                    "SELECT item_text, quantity, stock_qty FROM purchase_line")) {
                assertThat(rs.next()).isTrue();
                // 日本語（半角カナ含む）が化けずに往復すること
                assertThat(rs.getString(1)).isEqualTo("ｷｬﾍﾞﾂ 1/2");
                // 小数が丸められていないこと
                assertThat(rs.getBigDecimal(2).doubleValue()).isEqualTo(1.5);
                assertThat(rs.getBigDecimal(3).doubleValue()).isEqualTo(1600.0);
            }
        }
    }

    @Test
    @DisplayName("存在しない食材は紐付けられない（外部キーが本当に効いている）")
    void foreign_key_is_enforced() throws Exception {
        try (Connection connection = freshSchema("mig_fk");
             Statement statement = connection.createStatement()) {

            statement.execute("SET search_path TO mig_fk");
            statement.execute("""
                    INSERT INTO purchase
                      (purchased_on, store_name, total_amount, received_on, stored_at,
                       paper_retention_required, reg_verify_status, evidence_type,
                       deduction_rate_percent, payment_method, deleted)
                    VALUES
                      (DATE '2026-08-31', 'テスト商店', 100, DATE '2026-08-31',
                       TIMESTAMP '2026-08-31 21:00:00', FALSE, 'NONE',
                       'NOT_QUALIFIED', 80, 'CASH', FALSE)
                    """);

            List<String> failures = new ArrayList<>();
            try {
                statement.execute("""
                        INSERT INTO purchase_line
                          (purchase_id, line_no, item_text, amount,
                           tax_rate_percent, category, ingredient_id)
                        VALUES (1, 1, 'まぼろしの食材', 100, 8, 'FOOD', 999999)
                        """);
            } catch (SQLException expected) {
                failures.add(expected.getMessage());
            }
            // 在庫の記録が、存在しない食材を指したまま残るのを DB 側で止める
            assertThat(failures).isNotEmpty();
        }
    }
}
