-- ============================================================================
--  V18 : レシピの「その他材料費」
-- ============================================================================
--  店主の指摘：「レシピ原価表で食材を g 数しか編集できない。食材入れずに
--  原価だけ入れて保存できないの？」
--
--  原価を知りたいだけの商品にも、全食材の g 数登録を強いていた。
--  油・塩・ソースのように量を測らないものもある（設計の未解決質問⑦）。
--  設計は docs\レシピのその他材料費-設計-20260916.md。
--
--  ★ なぜ recipe_line を拡張しなかったか
--    「食材なしのレシピ行」を許す案（ingredient_id を NULL 可にする）は却下した。
--    RecipeLineRepository.findAllWithRelations が join fetch ＝ 内部結合なので、
--    食材なしの行は例外も警告も出さずに結果から消える。原価表と消費計算から
--    同時に落ちて「保存したのに出てこない・消せない行」になる。静かに壊れる。
--
--  ★ 別テーブルにする利点は「除外を書かなくてよい」こと
--    金額はレシピ行ではないので、消費計算（ConsumptionService）からは
--    原理的に見えない。除外処理が要らない＝除外の書き忘れが起きない。
--    在庫まわりのコードは 1 行も変えていない。
--
--  ★ 既存 13 テーブルには列を足していない（Step 1〜3 からの約束）
--    app.inventory.enabled=false で在庫モジュールを切ったとき、
--    既存テーブルに痕跡が残らない。
--
--  ★ 外部キーに ON DELETE CASCADE は付けない
--    recipe_line と揃える。商品削除の後片付けは MenuService.deleteItem が
--    明示的にやる（消す順番をコード側で読めるようにしておくため）。
--    ここを CASCADE にすると、recipe_line だけコードで消して
--    other_cost は DB が黙って消す、という非対称ができる。
-- ----------------------------------------------------------------------------

CREATE TABLE recipe_other_cost (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 商品 1 つにつき 1 件。2 件あるとどちらを原価に足すか決まらないので UNIQUE。
    menu_item_id         BIGINT       NOT NULL,

    -- 円・税込。金額は必ず int（円）、価格は税込で保持、が規約。
    -- 税抜は TaxCalculator で割り戻す（税率をここに持たない）。
    -- 0 と負数は入れない。0 は「検討した結果 0 円」と「まだ入れていない」が
    -- 区別できなくなるので行ごと消す。負数は原価が減って原価率が嘘になる。
    amount_including_tax INT          NOT NULL,

    -- 「ソース・青のり・かつお節」など。何をまとめた金額かを残すため。
    memo                 VARCHAR(100),

    CONSTRAINT fk_recipe_other_cost_menu_item
        FOREIGN KEY (menu_item_id) REFERENCES menu_item (id),
    CONSTRAINT uq_recipe_other_cost_menu_item
        UNIQUE (menu_item_id),
    CONSTRAINT ck_recipe_other_cost_amount
        CHECK (amount_including_tax > 0)
);
