-- ============================================================================
--  V2 : 仕入れ・在庫モジュール（Step 1「お金の層」）のテーブル
-- ============================================================================
--  既存の 13 テーブルは V1 として「もうある」ことにしています（baseline）。
--  この V2 が、Flyway が実際に流す最初の SQL です。
--
--  ★ 既存のテーブルには一切触れていません。
--    2026-08-18 に既存テーブルへ NOT NULL 列を足して起動不能にした事故があるため、
--    追加はすべて新しいテーブルで行う、という方針にしています。
--
--  ★ H2（開発）と PostgreSQL（本番）の両方で通る書き方に寄せています。
--    - BIGINT GENERATED BY DEFAULT AS IDENTITY … 両対応の採番
--    - VARCHAR / INTEGER / BOOLEAN / DATE / TIMESTAMP / NUMERIC … 共通の型
--    - CLOB / text のように名前が分かれる型は使わない
-- ============================================================================


-- ----------------------------------------------------------------------------
--  税率マスタ : 「いつからいつまで、この区分は何 % か」
-- ----------------------------------------------------------------------------
--  税率をコードに書かずここに置くことで、税制改正が「行の追加」で済みます。
--  施行日を未来にして先に登録できるので、当日の設定変更忘れが起きません。
-- ----------------------------------------------------------------------------
CREATE TABLE tax_rate_period (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_class   VARCHAR(30)  NOT NULL,
    rate_percent INTEGER      NOT NULL,
    valid_from   DATE         NOT NULL,
    valid_to     DATE,
    note         VARCHAR(200)
);

CREATE INDEX idx_tax_rate_period_lookup ON tax_rate_period (rate_class, valid_from);


-- ----------------------------------------------------------------------------
--  控除率マスタ : 免税事業者などからの仕入れを何 % 引けるか（経過措置）
-- ----------------------------------------------------------------------------
--  80% → 70%（2026-10-01〜）→ 50% → 30% → 廃止、と段階的に下がります。
--  2031 年の終了まで法律で決まっているので、初期データで全部入れておきます。
-- ----------------------------------------------------------------------------
CREATE TABLE deduction_rate_period (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_percent INTEGER      NOT NULL,
    valid_from   DATE         NOT NULL,
    valid_to     DATE,
    note         VARCHAR(200)
);

CREATE INDEX idx_deduction_rate_period_lookup ON deduction_rate_period (valid_from);


-- ----------------------------------------------------------------------------
--  仕入れ・経費（レシート 1 枚）
-- ----------------------------------------------------------------------------
--  電子帳簿保存法（スキャナ保存）のための列が多く含まれます。
--    stored_at                … 保存を終えた時刻。サーバの時計で 1 度だけ入れ、以後変えない
--    equivalence_checked_at   … 紙と画像を見比べた時刻。ここが入って初めて紙を捨ててよい
--    paper_retention_required … 入力期限を過ぎた分は紙のまま保管する必要がある
--    deleted / deleted_at     … 削除は行を消さずフラグで行う（削除済みも検索できる必要がある）
--
--  検索の 3 項目（取引年月日・取引金額・取引先）は索引を張っています。
--  「探せること」が法律上の要件なので、性能の都合ではなく必須の設備です。
-- ----------------------------------------------------------------------------
CREATE TABLE purchase (
    id                       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 検索 3 項目
    purchased_on             DATE          NOT NULL,
    store_name               VARCHAR(120)  NOT NULL,
    total_amount             INTEGER       NOT NULL,

    -- 入力期限まわり
    received_on              DATE          NOT NULL,
    stored_at                TIMESTAMP     NOT NULL,
    equivalence_checked_at   TIMESTAMP,
    paper_retention_required BOOLEAN       NOT NULL,

    -- インボイス制度まわり
    reg_number_raw           VARCHAR(60),
    reg_number               VARCHAR(14),
    reg_verify_status        VARCHAR(20)   NOT NULL,
    evidence_type            VARCHAR(30)   NOT NULL,
    deduction_rate_percent   INTEGER       NOT NULL,

    -- そのほか
    payment_method           VARCHAR(20)   NOT NULL,
    image_path               VARCHAR(200),
    ocr_json                 VARCHAR(20000),
    memo                     VARCHAR(300),
    created_by               BIGINT,

    -- 論理削除
    deleted                  BOOLEAN       NOT NULL,
    deleted_at               TIMESTAMP,
    delete_reason            VARCHAR(200)
);

CREATE INDEX idx_purchase_purchased_on ON purchase (purchased_on);
CREATE INDEX idx_purchase_store_name   ON purchase (store_name);


-- ----------------------------------------------------------------------------
--  仕入れの明細（レシートの 1 行）
-- ----------------------------------------------------------------------------
--  税率とカテゴリを「行」に持つのが要点です。
--  スーパーのレシートには食材（軽減 8%）と洗剤（標準 10%）が並ぶため、
--  レシート単位では表現できません。
--
--  tax_amount が NULL を許すのは、適格簡易請求書が
--  「税額」か「適用税率」のどちらか一方を書けばよいためです（印字なしは合法）。
-- ----------------------------------------------------------------------------
CREATE TABLE purchase_line (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id      BIGINT        NOT NULL,
    line_no          INTEGER       NOT NULL,
    item_text        VARCHAR(120)  NOT NULL,
    quantity         NUMERIC(12,3),
    amount           INTEGER       NOT NULL,
    tax_rate_percent INTEGER       NOT NULL,
    tax_amount       INTEGER,
    category         VARCHAR(20)   NOT NULL,

    CONSTRAINT fk_purchase_line_purchase
        FOREIGN KEY (purchase_id) REFERENCES purchase (id)
);

CREATE INDEX idx_purchase_line_purchase ON purchase_line (purchase_id);
