-- ============================================================================
--  V3 : 在庫の層（Step 2）
-- ============================================================================
--  Step 1 は「お金の層」でした。レシートを保存し、月の経費と原価率が見える。
--  この V3 で、その仕入れが「棚の上の物」につながります。
--
--  ★ ここでも既存の 13 テーブルには触れていません。
--    唯一の変更は purchase_line（V2 でこちらが作ったテーブル）への列追加で、
--    どちらも NULL 可なので既存の行はそのまま生きます。
--    2026-08-18 の起動不能事故（既存テーブルへの NOT NULL 列追加）と同じ形を避けています。
-- ============================================================================


-- ----------------------------------------------------------------------------
--  食材マスタ
-- ----------------------------------------------------------------------------
--  ★ 在庫の数量はこのテーブルに持ちません。
--    現在庫は「棚卸し＋入庫−消費＋補正」で毎回計算します。
--    数量を持つと「計算した値」と「保存した値」が食い違ったとき、
--    どちらが正しいのか誰にも分からなくなるためです（銀行口座と同じ考え方）。
--
--  ★ active は論理削除です。行は消しません。
--    過去の仕入れ明細・棚卸し・レシピがこの行を指しているので、
--    消すと去年の原価が計算できなくなります。
-- ----------------------------------------------------------------------------
CREATE TABLE ingredient (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(60)   NOT NULL,
    unit              VARCHAR(20)   NOT NULL,
    low_threshold_qty NUMERIC(12,3),
    cost_override     NUMERIC(12,4),
    active            BOOLEAN       NOT NULL,
    sort_order        INTEGER       NOT NULL,
    memo              VARCHAR(200),

    CONSTRAINT uk_ingredient_name UNIQUE (name)
);


-- ----------------------------------------------------------------------------
--  入り数の記憶（レシート品名 → 食材、1個あたりの量）
-- ----------------------------------------------------------------------------
--  レシートには「エリンギ 120」としか書かれておらず、グラム数はどこにもありません。
--  そこで 1 回だけ「これは 100g」と教えてもらい、次からは自動で換算します。
--
--  alias_text は必ず正規化済み（AliasText.normalize）の値を入れます。
--  生の文字列だと「ｷｬﾍﾞﾂ」と「キャベツ」が別行になり、何度も教え直すはめになります。
--
--  qty_per_unit が NULL = まだ教わっていない。この状態でも仕入れは保存でき、
--  画面で黄色く表示されます。入力を止めないことを優先しています。
-- ----------------------------------------------------------------------------
CREATE TABLE item_alias (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_text    VARCHAR(120)  NOT NULL,
    sample_text   VARCHAR(120),
    ingredient_id BIGINT        NOT NULL,
    qty_per_unit  NUMERIC(12,3),
    updated_at    TIMESTAMP     NOT NULL,

    CONSTRAINT uk_item_alias_text UNIQUE (alias_text),
    CONSTRAINT fk_item_alias_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)
);


-- ----------------------------------------------------------------------------
--  棚卸し・廃棄・まかない
-- ----------------------------------------------------------------------------
--  type = RESET   … 実測。ここが在庫計算の起点になり、これより前は忘れる
--  type = ADJUST  … 増減。捨てた・まかないで使った（減らすときは負の数）
--
--  ★ taken_on は日付です（時刻ではありません）。
--    突き合わせる相手が仕入れ（日付）と注文（営業日）なので、
--    片方だけ細かくても比べようがないためです。
--
--  ★ この行は訂正しません。間違えたら打ち消す行を足します。
--    「あの日は 1200g と数えた」は、あとから見て正しくなくても事実です。
-- ----------------------------------------------------------------------------
CREATE TABLE stocktake (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT        NOT NULL,
    taken_on      DATE          NOT NULL,
    recorded_at   TIMESTAMP     NOT NULL,
    type          VARCHAR(20)   NOT NULL,
    quantity      NUMERIC(12,3) NOT NULL,
    reason        VARCHAR(20)   NOT NULL,
    memo          VARCHAR(200),
    created_by    BIGINT,

    CONSTRAINT fk_stocktake_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)
);

CREATE INDEX idx_stocktake_ingredient ON stocktake (ingredient_id, taken_on);


-- ----------------------------------------------------------------------------
--  仕入れ明細から在庫への橋
-- ----------------------------------------------------------------------------
--  どちらも NULL 可です。これは手抜きではなく設計です:
--    ingredient_id が NULL … 洗剤・光熱費など、経費だが在庫ではないもの
--    stock_qty     が NULL … 食材だが、まだ入り数を教わっていないもの
--
--  「紐付けないと保存できない」にすると、忙しい日にレシート入力の手が止まります。
--  お金の記録は紐付けの有無と関係なく完全なので、あとから紐付ければ在庫にも入ります。
-- ----------------------------------------------------------------------------
ALTER TABLE purchase_line ADD COLUMN ingredient_id BIGINT;
ALTER TABLE purchase_line ADD COLUMN stock_qty     NUMERIC(12,3);

ALTER TABLE purchase_line
    ADD CONSTRAINT fk_purchase_line_ingredient
    FOREIGN KEY (ingredient_id) REFERENCES ingredient (id);

CREATE INDEX idx_purchase_line_ingredient ON purchase_line (ingredient_id);
