-- ============================================================================
--  V4 : レシピの層（Step 3）
-- ============================================================================
--  Step 2 で仕入れが在庫につながった。この V4 で、注文が在庫を減らすようになる。
--
--  ★ menu_item には本物の外部キーを張る。
--    レシピは「履歴」ではなく「いまの設定」なので、整合性は DB に守らせてよい。
--    過去の注文明細（order_line）が品名も価格もスナップショットで持つのとは
--    役割が違う。あちらは「あの日いくらで売った」という事実の記録で、
--    メニューを消しても消えてはいけないもの。
--
--  ★ 既存の menu_item テーブル自体には触れていない（列を足していない）。
--    参照するだけ。既存の13テーブルは V2・V3 と同じく無変更のまま。
-- ============================================================================

CREATE TABLE recipe_line (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id  BIGINT        NOT NULL,
    ingredient_id BIGINT        NOT NULL,
    qty_per_item  NUMERIC(12,3) NOT NULL,
    memo          VARCHAR(100),

    CONSTRAINT fk_recipe_line_menu_item
        FOREIGN KEY (menu_item_id) REFERENCES menu_item (id),
    CONSTRAINT fk_recipe_line_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)
);

CREATE INDEX idx_recipe_line_menu_item  ON recipe_line (menu_item_id);
CREATE INDEX idx_recipe_line_ingredient ON recipe_line (ingredient_id);
